Add version number option to pinter
plancklang/pinter pull request #8
Opened 2020-11-26 22:03 UTC by JakeRoggenbuck

2020-11-26 22:07 UTC, JakeRoggenbuck commented
[6b5d](https://github.com/plancklang/pinter/pull/8/commits/6b5d99a24a0ea9f326f8b22f2e1ae5b773995c41) fixed the issue with [6f4e](https://github.com/plancklang/pinter/pull/8/commits/6f4eac36a4cb4f1f379251a9d2fc2d40e1609bc9)

2020-11-27 02:49 UTC, adamhutchings requested changes
It's better if VERSION is a float.

2020-11-27 02:49 UTC, adamhutchings commented on src/util.h
> +#define VERSION "0.1"
Could you define VERSION as `0.1` and not. `"0.1"` ?

2020-11-27 02:49 UTC, adamhutchings commented on src/main.c
> +	printf("Pinter %s\n", VERSION);
Change to `%f`, I believe. Make sure to test.

2020-11-27 04:44 UTC, JakeRoggenbuck commented
If it’s a float and we printf as %f, it will print 0.1000000 and I don’t know how to change that. I agree we should have the value something more space efficient. Can we print a float as a string?

2020-11-27 17:30 UTC, merged